CartPole1:
  env_id: CartPole-v1
  capacity: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_final: 0.05
  discount_factor: 0.99
  learning_rate: 0.001
  sync_rate: 10
  stop_on_reward: 100000

FlappyBird1:
  env_id: FlappyBird-v0
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000